apiVersion: v1
kind: Pod
metadata:
  name: wordpress-app
  labels:
    app: web
spec:
  containers:
    - name: front-end
      image: wordpress
      ports:
        - containerPort: 80
    - name: database
      image: mysql:5.7
      ports:
        - containerPort: 3306