version: '3'

services:
     portainer:
          image: portainer/portainer
          ports:
               - 8001:8000
               - 9000:9000
          volumes:
              - /var/run/docker.sock:/var/run/docker.sock