FROM javacream/javabase:1.0
ADD org.javacream.training.docker.java.fileapplication-1.0-SNAPSHOT.jar ${JAVA_LIB_DIR}/app.jar
ENV JAVA_MAIN_CLASS org.javacream.training.docker.fileapplication.FileTransferUtil
VOLUME /input